
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "8082:8082"
      - "9092:9092"
    volumes:
      - h2-data:/opt/h2-data
    networks:
      default:
        ipv4_address: 192.168.33.11

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:8080"
    networks:
      default:
        ipv4_address: 192.168.33.10
    depends_on:
      - "db"

volumes:
  h2-data:
    driver: local

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.33.0/24
